Pulls snippet with XHR
maryvilledev/codesplain-embedded pull request #13
Opened 2017-04-24 15:16 UTC by dane-johnson

The snippet is now brought in dynamically via an XHR request.
Closes #4

2017-04-24 16:04 UTC, Hopding requested changes

2017-04-24 16:04 UTC, Hopding commented on src/containers/AppBody.js
>        });
Perhaps we should indicate that the requested snippet does not exist if the Promise fails?

2017-04-24 16:09 UTC, Hopding commented
Also, https://github.com/maryvilledev/codesplain-embedded/blob/xhrSnippet/public/snippet.json should probably be removed with this PR, since it is no longer going to be used.

2017-04-24 17:15 UTC, dane-johnson commented on src/containers/AppBody.js
>        });
I'm thinking that kinda needs to be it's own story, because I think the entire view should change when the snippet is broken.

2017-04-24 18:12 UTC, Hopding commented on src/containers/AppBody.js
>        });
Fair enough

2017-04-24 18:13 UTC, Hopding approved these changes

2017-04-25 17:05 UTC, solkaz approved these changes
Looks good, I'd like clarification for my question. Otherwise, :shipit:

2017-04-25 17:05 UTC, solkaz commented on src/containers/AppBody.jsx
> +    const [user, snippet] = snippetKey.split("/");
How do we know that the snippet key contains only one '/' character?

2017-04-25 17:16 UTC, dane-johnson commented on src/containers/AppBody.jsx
> +    const [user, snippet] = snippetKey.split("/");
It could be verified when runestone compiles, although that isn't yet implemented.

2017-04-25 17:21 UTC, solkaz commented on src/containers/AppBody.jsx
> +    const [user, snippet] = snippetKey.split("/");
Now that I think about it, the key should be URI encoded so there _shouldn't_ be a '/', but I might be mistaken

2017-04-25 17:24 UTC, dane-johnson commented on src/containers/AppBody.jsx
> +    const [user, snippet] = snippetKey.split("/");
It's not from a URI its a data tag on the parent element.

2017-04-25 17:55 UTC, solkaz commented on src/containers/AppBody.jsx
> +    const [user, snippet] = snippetKey.split("/");
Right, but it still is a key that refers to a specific resource, so we do need to make sure that it is URI friendly.

2017-04-25 18:48 UTC, merged